import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

import type { DayEntry } from '../lib/entries'
import { describeEntry } from '../lib/entries'
import { duration, percent, timeOfDay } from '../lib/format'
import { IconApps, IconClose, IconPencil, IconTrash } from './Icons'

const WIDTH = 356
/** Kept off the window edge so the card never looks clipped. */
const MARGIN = 12

export interface EntryPopoverProps {
  entry: DayEntry
  /** Where the block sits on screen, so the card can be anchored beside it. */
  anchor: DOMRect | null
  color: string
  /** Tracked seconds for the whole day — the denominator of the ring. */
  dayTotalSeconds: number
  onClose(): void
  onEdit(): void
  onDelete(): void
}

const PRODUCTIVITY_LABEL: Record<string, string> = {
  productive: 'Focus',
  neutral: 'Neutral',
  distracting: 'Distraction',
  idle: 'Away',
  event: 'Scheduled',
}

/**
 * The block detail card.
 *
 * Everything on it is derived from the sessions folded into the block — there is
 * no per-entry field the store does not already hold, and nothing here is
 * generated by anything but arithmetic. The one thing a commercial tracker puts
 * in this slot that OpenTime cannot is a billable amount: there are no rates and
 * no clients in the data model, so that row is simply absent rather than faked.
 */
export function EntryPopover({
  entry,
  anchor,
  color,
  dayTotalSeconds,
  onClose,
  onEdit,
  onDelete,
}: EntryPopoverProps) {
  const card = useRef<HTMLDivElement>(null)
  const [pos, setPos] = useState<{ top: number; left: number; origin: string } | null>(null)
  const [confirming, setConfirming] = useState(false)

  // Anchoring happens before paint: a card that appears at 0,0 and then jumps
  // to the block is worse than one that appears a frame later.
  useLayoutEffect(() => {
    if (!anchor) {
      setPos(null)
      return
    }
    const height = card.current?.offsetHeight ?? 320
    const viewportW = window.innerWidth
    const viewportH = window.innerHeight
    const toRight = anchor.right + 10
    const fitsRight = toRight + WIDTH + MARGIN <= viewportW
    const left = fitsRight ? toRight : Math.max(MARGIN, anchor.left - WIDTH - 10)
    const top = Math.min(
      Math.max(MARGIN, anchor.top - 8),
      Math.max(MARGIN, viewportH - height - MARGIN)
    )
    // The entrance scales from the side the block is on, so the card reads as
    // growing out of it rather than landing beside it.
    setPos({ top, left, origin: fitsRight ? 'top left' : 'top right' })
  }, [anchor, entry.id])

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    const onDown = (e: MouseEvent) => {
      if (!card.current?.contains(e.target as Node)) onClose()
    }
    document.addEventListener('keydown', onKey)
    // Deferred by a tick so the click that opened the card does not close it.
    const timer = window.setTimeout(() => document.addEventListener('mousedown', onDown), 0)
    return () => {
      document.removeEventListener('keydown', onKey)
      document.removeEventListener('mousedown', onDown)
      window.clearTimeout(timer)
    }
  }, [onClose])

  const share = dayTotalSeconds > 0 ? entry.seconds / dayTotalSeconds : 0
  const editable = entry.kind !== 'event'
  const deletable = entry.kind === 'session'

  /*
   * Portalled to the body on purpose.
   *
   * `position: fixed` is only relative to the viewport while no ancestor
   * establishes a containing block — and the view transition in styles.css is a
   * transform animation with `fill: both`, which does exactly that for as long
   * as it stays applied. Rendered in place, this card lands offset by the width
   * of the sidebar and the height of the title bar, which looks like a
   * co-ordinate bug and is really a stacking one.
   */
  return createPortal(
    <div
      className="popover"
      ref={card}
      /* Keyed so opening a different block replays the entrance — the card
         teleporting between blocks with no motion reads as a glitch. */
      key={entry.id}
      role="dialog"
      aria-label={entry.label}
      style={
        {
          width: WIDTH,
          top: pos?.top ?? -9999,
          left: pos?.left ?? -9999,
          '--origin': pos?.origin ?? 'top left',
        } as React.CSSProperties
      }
    >
      <div className="popover-head">
        <span className="popover-dot" style={{ background: color }} />
        <span className="popover-workspace">Personal</span>
        <Ring share={share} color={color} />
        <div className="popover-actions">
          {editable ? (
            <button className="icon-btn" onClick={onEdit} title="Edit this block">
              <IconPencil size={15} />
            </button>
          ) : null}
          {deletable ? (
            <button
              className="icon-btn danger"
              onClick={() => setConfirming(true)}
              title="Delete this block"
            >
              <IconTrash size={15} />
            </button>
          ) : null}
          <button className="icon-btn" onClick={onClose} title="Close">
            <IconClose size={15} />
          </button>
        </div>
      </div>

      {confirming ? (
        <div className="popover-confirm">
          <span>
            {entry.sessions.length > 1
              ? `Delete all ${entry.sessions.length} blocks in this entry?`
              : 'Delete this block?'}{' '}
            The time is removed from your day.
          </span>
          <div className="row">
            <button className="btn danger small" onClick={onDelete}>
              Delete
            </button>
            <button className="btn ghost small" onClick={() => setConfirming(false)}>
              Cancel
            </button>
          </div>
        </div>
      ) : null}

      <div className="popover-title-row">
        <h3 className="popover-title">{entry.label}</h3>
        <span className="popover-duration">{duration(entry.seconds)}</span>
      </div>

      <div className="popover-when">
        {timeOfDay(entry.start)} – {timeOfDay(entry.end)}
      </div>

      <div className="popover-chips">
        <span className={`chip ${entry.productivity}`}>
          {PRODUCTIVITY_LABEL[entry.productivity] || entry.productivity}
        </span>
        {entry.titles.length ? (
          <span className="chip" title={entry.titles[0]}>
            {entry.titles[0]}
          </span>
        ) : null}
        {entry.edited ? <span className="chip">Corrected by hand</span> : null}
        {entry.demo ? <span className="chip warn">Demo data</span> : null}
      </div>

      {entry.note ? <p className="popover-note">“{entry.note}”</p> : null}
      <p className="popover-body">{describeEntry(entry)}</p>

      {entry.apps.length ? (
        <>
          <div className="popover-section">
            <IconApps size={14} />
            Apps &amp; websites
          </div>
          <div className="popover-apps">
            {entry.apps.slice(0, 6).map((app) => (
              <div className="popover-app" key={app.name}>
                <b>{percent(app.share)}</b>
                <span className="popover-app-bar">
                  <i style={{ width: `${Math.max(3, app.share * 100)}%`, background: color }} />
                </span>
                <span className="popover-app-name" title={app.name}>
                  {app.name}
                </span>
                <span className="popover-app-time">{duration(app.seconds)}</span>
              </div>
            ))}
          </div>
        </>
      ) : null}
    </div>,
    document.body
  )
}

/** The share-of-day badge: a thin ring with the number inside it. */
function Ring({ share, color }: { share: number; color: string }) {
  const size = 34
  const stroke = 2.6
  const radius = (size - stroke) / 2
  const circumference = 2 * Math.PI * radius
  const dash = Math.min(1, Math.max(0, share)) * circumference

  return (
    <span className="popover-ring" title="Share of the day tracked">
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} aria-hidden="true">
        <g transform={`rotate(-90 ${size / 2} ${size / 2})`}>
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke="var(--line)"
            strokeWidth={stroke}
          />
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke={color}
            strokeWidth={stroke}
            strokeLinecap="round"
            strokeDasharray={`${dash} ${circumference - dash}`}
          />
        </g>
      </svg>
      <b>{percent(share)}</b>
    </span>
  )
}
